services:
  backend:
    build: .
    env_file:
      - .env
    command: uv run fastapi run backend/app/main.py --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  worker-pdf:
    build: .
    env_file:
      - .env
    command: uv run celery -A backend.app.celery_tasks.celery_init worker --loglevel=info --pool=prefork -c 4 -Q pdf_queue
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 512M

  worker-email:
    build: .
    env_file:
      - .env
    command: uv run celery -A backend.app.celery_tasks.celery_init worker --loglevel=info --pool=threads -c 100 -Q email_queue
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 256M

  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: personalcrm
      LC_MESSAGES: en_US.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data: