[project]
name = "personalcrm"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.5",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.140.0",
    "psycopg[binary]>=3.3.4",
    "pwdlib[argon2]>=0.3.0",
    "pyjwt>=2.13.0",
    "python-ulid>=4.0.1",
    "sqlmodel>=0.0.39",
    "uvicorn>=0.51.0",
]

[tool.uv.workspace]
members = [
    ".",
]

[tool.uv.sources]
personalcrm = { workspace = true }

[dependency-groups]
dev = [
    "mypy>=2.3.0",
    "personalcrm",
    "pytest>=9.1.1",
    "ruff>=0.16.0",
]

[tool.ruff]
line-lenght = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.mypy]
python_version = "3.12"
strict = false
ignore_missing_imports = true
exclude = ["alembic/"]

[tool.fastapi]
entrypoint = "backend.app.main:app"

