"""Добавление столбца mid_amount в Invoice

Revision ID: 0852b28f3bc2
Revises: 9562be7ee13a
Create Date: 2026-08-01 13:28:53.265562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0852b28f3bc2'
down_revision: Union[str, Sequence[str], None] = '9562be7ee13a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('mid_amount', sa.Numeric(precision=8, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'mid_amount')
    # ### end Alembic commands ###
