"""Изменение поведения моделей

Revision ID: 73b239099717
Revises: 1b9ba934970a
Create Date: 2026-07-31 13:17:32.307167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b239099717'
down_revision: Union[str, Sequence[str], None] = '1b9ba934970a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('full_name_index'), table_name='client')
    op.create_index('full_name_index', 'client', ['first_name', 'last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('full_name_index', table_name='client')
    op.create_index(op.f('full_name_index'), 'client', ['first_name', 'last_name'], unique=True)
    # ### end Alembic commands ###
