"""Добавление столбца due_time в invoice

Revision ID: 9562be7ee13a
Revises: e2d1a4bb5d03
Create Date: 2026-08-01 13:10:46.910475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9562be7ee13a'
down_revision: Union[str, Sequence[str], None] = 'e2d1a4bb5d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('due_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'due_date')
    # ### end Alembic commands ###
