"""Добавление label для invoice

Revision ID: ca837833d21f
Revises: cbcdd89ebcaa
Create Date: 2026-08-01 16:44:43.403230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ca837833d21f'
down_revision: Union[str, Sequence[str], None] = 'cbcdd89ebcaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.create_index(op.f('ix_invoice_label'), 'invoice', ['label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_label'), table_name='invoice')
    op.drop_column('invoice', 'label')
    # ### end Alembic commands ###
