"""Добавление дефолтного параметра для decimal атри

Revision ID: cbcdd89ebcaa
Revises: 0852b28f3bc2
Create Date: 2026-08-01 13:50:23.455003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbcdd89ebcaa'
down_revision: Union[str, Sequence[str], None] = '0852b28f3bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
