"""Добавление уникальности для столбцов никнейма клиента и user_id

Revision ID: e2d1a4bb5d03
Revises: 73b239099717
Create Date: 2026-07-31 13:34:44.413788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2d1a4bb5d03'
down_revision: Union[str, Sequence[str], None] = '73b239099717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_username_for_user', 'client', ['user_id', 'username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_username_for_user', 'client', type_='unique')
    # ### end Alembic commands ###
