"""Currency added

Revision ID: 10b133319392
Revises: 1d7e690e3dbf
Create Date: 2026-09-29 19:32:48.571488

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10b133319392'
down_revision: Union[str, Sequence[str], None] = '1d7e690e3dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deals', 'currency',
               existing_type=postgresql.ENUM('USD', 'EUR', 'RUB', name='currency'),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('invoices', 'currency',
               existing_type=postgresql.ENUM('USD', 'EUR', 'RUB', name='currency'),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'currency',
               existing_type=sa.String(length=255),
               type_=postgresql.ENUM('USD', 'EUR', 'RUB', name='currency'),
               existing_nullable=False)
    op.alter_column('deals', 'currency',
               existing_type=sa.String(length=255),
               type_=postgresql.ENUM('USD', 'EUR', 'RUB', name='currency'),
               existing_nullable=False)
    # ### end Alembic commands ###
