"""Added number for invoice

Revision ID: 1d7e690e3dbf
Revises: 298822063119
Create Date: 2026-09-17 01:06:41.892645

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1d7e690e3dbf'
down_revision: Union[str, Sequence[str], None] = '298822063119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_counters',
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('last_number', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_counters')
    # ### end Alembic commands ###
