"""Fix Invoice table

Revision ID: 298822063119
Revises: dda7e75d8104
Create Date: 2026-09-16 21:47:49.204470

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '298822063119'
down_revision: Union[str, Sequence[str], None] = 'dda7e75d8104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
