"""New rev

Revision ID: 98ae63bb7b6b
Revises: 28be7a539b23
Create Date: 2026-08-30 14:25:13.130980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ae63bb7b6b'
down_revision: Union[str, Sequence[str], None] = '28be7a539b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('currency', sa.Enum('USD', 'EUR', 'RUB', name='currency'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal', 'currency')
    # ### end Alembic commands ###
