"""initial schema

Revision ID: d61642543cd0
Revises:
Create Date: 2026-09-08 18:53:15.378376

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd61642543cd0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('full_name', sa.String(length=255), nullable=False),
        sa.Column('username', sa.String(length=255), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('timezone', sa.String(length=32), nullable=False),
        sa.Column('id', sa.String(length=26), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'ix_username_lower',
        'users',
        [sa.literal_column('lower(username)')],
        unique=True,
    )
    op.create_index(
        'ix_users_email_lower',
        'users',
        [sa.literal_column('lower(email)')],
        unique=True,
    )
    op.create_table(
        'clients',
        sa.Column('client_name', sa.String(length=50), nullable=False),
        sa.Column('organization', sa.String(length=50), nullable=True),
        sa.Column('email', sa.String(length=100), nullable=True),
        sa.Column('phone', sa.String(length=100), nullable=True),
        sa.Column('telegram', sa.String(length=100), nullable=True),
        sa.Column(
            'additional_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            'client_status',
            sa.Enum('lead', 'active', 'completed', 'blacklisted', name='client_status'),
            nullable=False,
        ),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('timezone', sa.String(length=32), nullable=True),
        sa.Column('user_id', sa.String(length=26), nullable=False),
        sa.Column('id', sa.String(length=26), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_clients_client_name'), 'clients', ['client_name'], unique=False
    )
    op.create_index(
        op.f('ix_clients_organization'), 'clients', ['organization'], unique=False
    )
    op.create_index(op.f('ix_clients_user_id'), 'clients', ['user_id'], unique=False)
    op.create_index(
        'ix_name_lower_title',
        'clients',
        [sa.literal_column('lower(client_name)')],
        unique=False,
    )
    op.create_table(
        'deals',
        sa.Column(
            'version', sa.BigInteger(), server_default=sa.text('1'), nullable=False
        ),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            'status',
            sa.Enum(
                'new',
                'in_progress',
                'on_review',
                'completed',
                'cancelled',
                name='deal_status',
            ),
            nullable=False,
        ),
        sa.Column(
            'currency', sa.Enum('USD', 'EUR', 'RUB', name='currency'), nullable=False
        ),
        sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
        sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('user_id', sa.String(length=26), nullable=False),
        sa.Column('client_id', sa.String(length=26), nullable=False),
        sa.Column('id', sa.String(length=26), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.CheckConstraint('amount >= 0', name='ck_deals_amount_positive'),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'idx_client_id__and__status', 'deals', ['client_id', 'status'], unique=False
    )
    op.create_index(op.f('ix_deals_client_id'), 'deals', ['client_id'], unique=False)
    op.create_index(op.f('ix_deals_deadline'), 'deals', ['deadline'], unique=False)
    op.create_index(op.f('ix_deals_name'), 'deals', ['name'], unique=False)
    op.create_index(op.f('ix_deals_user_id'), 'deals', ['user_id'], unique=False)
    op.create_table(
        'invoices',
        sa.Column('label', sa.String(length=50), nullable=False),
        sa.Column('number', sa.String(length=255), nullable=False),
        sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            'currency', sa.Enum('USD', 'EUR', 'RUB', name='currency'), nullable=False
        ),
        sa.Column(
            'status',
            sa.Enum(
                'draft', 'sent', 'paid', 'overdue', 'cancelled', name='invoice_status'
            ),
            nullable=False,
        ),
        sa.Column('due_date', sa.Date(), nullable=False),
        sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_paid', sa.Boolean(), nullable=False),
        sa.Column('user_id', sa.String(length=26), nullable=False),
        sa.Column('deal_id', sa.String(length=26), nullable=True),
        sa.Column('client_id', sa.String(length=26), nullable=False),
        sa.Column('id', sa.String(length=26), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.CheckConstraint('amount >= 0', name='ck_invoices_amount_positive'),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'number'),
    )
    op.create_index(
        op.f('ix_invoices_client_id'), 'invoices', ['client_id'], unique=False
    )
    op.create_index(op.f('ix_invoices_deal_id'), 'invoices', ['deal_id'], unique=False)
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_deal_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_client_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_deals_user_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_name'), table_name='deals')
    op.drop_index(op.f('ix_deals_deadline'), table_name='deals')
    op.drop_index(op.f('ix_deals_client_id'), table_name='deals')
    op.drop_index('idx_client_id__and__status', table_name='deals')
    op.drop_table('deals')
    op.drop_index('ix_name_lower_title', table_name='clients')
    op.drop_index(op.f('ix_clients_user_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_organization'), table_name='clients')
    op.drop_index(op.f('ix_clients_client_name'), table_name='clients')
    op.drop_table('clients')
    op.drop_index('ix_users_email_lower', table_name='users')
    op.drop_index('ix_username_lower', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
