"""User populates fix

Revision ID: dda7e75d8104
Revises: d61642543cd0
Create Date: 2026-09-10 21:57:21.711061

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'dda7e75d8104'
down_revision: Union[str, Sequence[str], None] = 'd61642543cd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
