"""Bug fix 002

Revision ID: df23b8c92a36
Revises: 106d358536aa
Create Date: 2026-10-02 22:04:47.043210

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df23b8c92a36'
down_revision: Union[str, Sequence[str], None] = '106d358536aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Fail before altering data; never silently truncate or invent relationships.
    op.execute("""
        DO $$ BEGIN
            IF EXISTS (
                SELECT 1 FROM invoices
                WHERE amount <= 0 OR deal_id IS NULL OR currency <> 'USD'
                   OR length(trim(label)) = 0 OR length(label) > 50
            ) OR EXISTS (
                SELECT 1 FROM deals
                WHERE currency <> 'USD' OR length(trim(name)) = 0
                   OR length(name) > 50 OR length(notes) > 5000
            ) THEN
                RAISE EXCEPTION 'Stage 2.4: incompatible existing data; correct amounts, links, currency and text before migrating';
            END IF;
        END $$;
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deals', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('deals', 'currency',
               existing_type=sa.VARCHAR(length=255),
               server_default='USD',
               existing_nullable=False)
    op.alter_column('deals', 'deadline',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True,  postgresql_using="(deadline AT TIME ZONE 'UTC')::date",)
    op.alter_column('deals', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=5000),
               existing_nullable=True)
    op.alter_column('invoices', 'currency',
               existing_type=sa.VARCHAR(length=255),
               server_default='USD',
               existing_nullable=False)
    op.alter_column('invoices', 'deal_id',
               existing_type=sa.VARCHAR(length=26),
               nullable=False)
    op.drop_constraint('ck_invoices_amount_positive', 'invoices', type_='check')


    op.create_check_constraint(
        'ck_invoices_amount_positive', 'invoices', 'amount > 0'
    )
    op.create_check_constraint(
        'ck_invoices_currency',
        'invoices',
        "currency = 'USD'",
    )

    op.create_check_constraint(
        'ck_deals_currency',
        'deals',
        "currency = 'USD'",
    )
    op.create_check_constraint(
        'ck_invoices_label_not_blank', 'invoices', 'length(trim(label)) > 0'
    )
    op.create_check_constraint(
        'ck_deals_name_not_blank', 'deals', 'length(trim(name)) > 0'
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('ck_invoices_currency', 'invoices', type_='check')
    op.drop_constraint('ck_deals_currency', 'deals', type_='check')
    op.drop_constraint('ck_invoices_label_not_blank', 'invoices', type_='check')
    op.drop_constraint('ck_deals_name_not_blank', 'deals', type_='check')
    op.drop_constraint('ck_invoices_amount_positive', 'invoices', type_='check')
    op.create_check_constraint(
        'ck_invoices_amount_positive', 'invoices', 'amount >= 0'
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'deal_id',
               existing_type=sa.VARCHAR(length=26),
               nullable=True)
    op.alter_column('invoices', 'currency',
               existing_type=sa.VARCHAR(length=255),
               server_default=None,
               existing_nullable=False)
    op.alter_column('deals', 'notes',
               existing_type=sa.String(length=5000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('deals', 'deadline',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               # Original time is lost on upgrade; restore midnight UTC.
               postgresql_using="deadline::timestamp AT TIME ZONE 'UTC'")
    op.alter_column('deals', 'currency',
               existing_type=sa.VARCHAR(length=255),
               server_default=None,
               existing_nullable=False)
    op.alter_column('deals', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
